### ISSUE TITLE
Terraform Orb: Github comment contains logs of refreshing state

### ISSUE THREAD

**Issue by Adam-McDevitt** [ovotech/circleci-orbs#224]
Hi

Out terraform plan comments have been blank recently and I opened a PR where I updated the orb to 1.8.1 as I saw that a fix for blank comments was in the change log.

But on the PR it's printed a large portion of the "refreshing state" log.

[https://github.com/ovotech/smart-bookings-terraform/pull/92](https://github.com/ovotech/smart-bookings-terraform/pull/92)

I guess the [compact_plan](https://github.com/ovotech/circleci-orbs/blob/bece8c0f819df892fef32d9719749bf0cc31448d/terraform/executor/compact_plan.py) code isn't working as expected?

**Comment by whyman** [comment]
Hi @Adam-McDevitt

My guess is that you are running an older executor image that does not include the `compact_plan` script. In this case we fall back to "cat" which is likely why you can see all the unrelated stuff.

**Comment by Adam-McDevitt** [comment]
I'll look into that, thanks @whyman !

**Comment by Adam-McDevitt** [comment]
Closing issue as the suggested solution worked

**Comment by whyman** [comment]
Probably we should include that script in the orb like the others, glad you got it sorted.
