### ISSUE TITLE
ovotech/terraform-v2@2 being broken

### ISSUE THREAD

**Issue by ksmnv** [ovotech/circleci-orbs#426]
Scripts fail with the same error:
`/bin/bash: line 16: terraform: command not found`

**Comment by ksmnv** [comment]
Trying to run ovotech/terraform docker image with the latest tag results in:
`docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/local/bin/terraform": stat /usr/local/bin/terraform: no such file or directory: unknown.`

**Comment by vickikozel** [comment]
Is there a workaround for terraform >=0.14 ?

**Comment by ksmnv** [comment]
For now a workaround is to use `docker:
      - image: ovotech/terraform:update-to-jukie-tfswitch_10-05-2022` instead of `executor: terraform/default` in your pipelines.
